# Generated by Django 5.2.9 on 2025-12-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
