# Generated by Django 5.2.9 on 2025-12-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='requirements',
            field=models.TextField(blank=True, help_text='Key features and deliverables expected'),
        ),
    ]
