# Generated by Django 5.2.9 on 2025-12-22 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_deadline_deal_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DealSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField(blank=True, default=list, help_text='List of links like GitHub, Drive, etc.')),
                ('files', models.JSONField(blank=True, default=list, help_text='List of uploaded file URLs')),
                ('notes', models.TextField(blank=True)),
                ('revision_round', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='deals.deal')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
