# Generated by Django 5.2.9 on 2025-12-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
