# Generated by Django 5.2.9 on 2025-12-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('resend', 'Resend (Email)'), ('termii', 'Termii (SMS)'), ('cloudinary', 'Cloudinary (Storage)'), ('paystack', 'Paystack (Gateway)'), ('flutterwave', 'Flutterwave (Gateway)')], max_length=50, unique=True)),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Third-Party Integration',
                'verbose_name_plural': 'Third-Party Integrations',
            },
        ),
    ]
