# Generated by Django 5.2.9 on 2025-12-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_thirdpartyintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
