# Generated by Django 5.2.9 on 2025-12-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='max_platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='min_platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='fee_payer',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('split', 'Split (50/50)')], default='split', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
