# Generated by Django 5.2.9 on 2026-01-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_platformsettings_max_platform_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('basic', 'Basic'), ('full', 'Full')], default='unverified', max_length=20),
        ),
    ]
